### ISSUE TITLE
Flashlight always showing on surfaces.

### ISSUE THREAD

**Issue by Knoir** [praydog/RE2-Mod-Framework#18]
Even when the flashlight is turned off and put away in-game, and "Manuel Flashlight" is disabled in the settings, I still see the beam shining on every surface to my right, which is something that never happened before I installed this mod. I don't know if this bug is common or if anyone else has encountered it, but I'd appreciate any ideas.

Example:
![screenshot 24](https://user-images.githubusercontent.com/43966775/52550633-7b67e580-2d9e-11e9-927a-b7072fe0a25e.png)

FOV largely increased to further demonstrate.

**Comment by praydog** [comment]
Not related to the flashlight mod, it's just a side effect of there being a light source next to the original third person camera. It will be fixed soon.

**Comment by Knoir** [comment]
Understood, thanks! Great mod, regardless. Having fun being scared all over again.

**Comment by praydog** [comment]
Added an option to disable this in latest build.
