### ISSUE TITLE
Hotkey for enabling/disabling mod and controller support

### ISSUE THREAD

**Issue by TesterNes** [praydog/RE2-Mod-Framework#21]
First of all congrats for your work. 
I think a hotkey for enabling/disabling the first person mod is needed as well as you did it for flashlight.
Then, it would be perfect if those hotkeys could be mapped by the xbox one controller. 
Thanks!

**Comment by praydog** [comment]
Working on it

**Comment by praydog** [comment]
Added in the latest build. Use third party software if you want to use your controller as a hotkey for now, support may come for controllers in the future.
