### ISSUE TITLE
Optional controller hoykey for Free Cam?

### ISSUE THREAD

**Issue by ShanestaDeJones** [praydog/RE2-Mod-Framework#27]
Would it be possible to make the "enable freecam" command mappable to a key or joystick? I was curious because I really like this option and it would be awesome to be able to toggle it on and off on the fly with my controller while playing. I notice it creates a sort of fixed camera angle experience and I was thinking to be able to map it to the right analog stick (R3) on ps4/xbox controllers and the 'c' key or something to that effect. Thanks for all of this work you've done putting this together, it's made my RE2 experience way better for sure! I will be most grateful if this was made possible!

**Comment by praydog** [comment]
Working on it

**Comment by praydog** [comment]
Added in the latest build. Use third party software if you want to use your controller as a hotkey for now, support may come for controllers in the future.

**Comment by ShanestaDeJones** [comment]
Thanks a bunch!
