### ISSUE TITLE
The 4th Survivor

### ISSUE THREAD

**Issue by Hyperbog** [praydog/RE2-Mod-Framework#3]
dinput8.dll - Extra Mode "The 4th Survivor" freezes at 10% during the loading screen. Must terminate the program via Task Manager.

**Comment by praydog** [comment]
Turn off the FirstPerson mod before going into a loading screen to be safe for now. Will try to figure out a way to fix it.

**Comment by zargatan** [comment]
I have a problem installed the mod but when the game starts it comes out double courses and it does not let me interact it is placed in the first person but it does not move with the mouse any solution

**Comment by Hyperbog** [comment]
Disabling the First Person View option prior to loading is a successful workaround. Thanks for providing a solution.

**Comment by praydog** [comment]
Hey, I've made a change. Can you download the latest version and check if the issue is fixed? I've went through multiple loading screens with no issue but want to make sure.
