### ISSUE TITLE
unable to find transform pattern

### ISSUE THREAD

**Issue by shinelucid** [praydog/RE2-Mod-Framework#39]
the message show since I got the dlc updates (v1.04) used to work fine before, up until the version 1.0.23 of the framework doesn't show the error but loads with defects, no options responding and crashing on the mesh hiding option and half of the menus at the bottom are missing...

**Comment by praydog** [comment]
I can't seem to get this to happen with the latest version of the game. Have you modified the executable in any way, is it the original straight from Steam? What DLCs do you have installed?

**Comment by M-Prime85** [comment]
I just had this same problem with the latest update, I have the steam version

**Comment by praydog** [comment]
Will look into it in a bit, I'm seeing the same issue after the update.

**Comment by xcg70** [comment]
Hey PrayDog, I too have the same issue and error,  I've got the DINPUT8 DLL in my RE2 folder and it used to work now it fails to initialize with the "Failed to find platform" error.

**Comment by xcg70** [comment]
Update, issue resolved by just downloading the latest RE DLINPUT.DLL  for the game from the link below (Github).

https://github.com/praydog/REFramework-nightly/releases
