### ISSUE TITLE
Double and even triple mouse

### ISSUE THREAD

**Issue by LagNeto** [praydog/RE2-Mod-Framework#4]
I have a problem, i install the mod and when the game start i have the Framework menu open with the mod activate but it shows me double mouse i cant interact with the framework neither with the game and if i open the steam overlay a third mouse appears and then i have to close the game with taskmanager because neither the keyboard work at that point.
I try disabling Geforce Experiencie overlay and rivaturner nothing work

**Comment by zargatan** [comment]
I have the same problem but I get double arrow and I can not interact with the mod to activate it is seen in first person but you can not move the view with the mouse

**Comment by SHIVAof** [comment]
Same for me, double cursor and mouse doesn't work in game nor in menu
