### ISSUE TITLE
RE3 Keybinds are randomly not working

### ISSUE THREAD

**Issue by kevmuller** [praydog/RE2-Mod-Framework#48]
i set the fov and such to my preferred way, start to play the game and suddenly throughout the level i wont be able to interact or pickup anything and eventually my ESC key stopped working and i couldn't walk at all(w,a,s,d). Not sure why this is happening, i thought at first it was the keybinds to toggle the mod that was getting in the way so i unbound the toggle but the issue stayed

**Comment by praydog** [comment]
I've potentially fixed this in the latest update. See if it works for you. They added some sort of anti-cheat to singleplayer which is why this is happening.

**Comment by kevmuller** [comment]
il test it out now! thanks for the quick response
