### ISSUE TITLE
RE3 crash at launch

### ISSUE THREAD

**Issue by GhoulRUS** [praydog/RE2-Mod-Framework#50]
Please consider DX12 support, as it has superior optimization to DX11 in RE3. I want to be able to play RE3 in first person, but my fps tanks on DX11

**Comment by Shawn-Holan** [comment]
How did you solve this? I'm having the same issue

**Comment by praydog** [comment]
@Shawn-Holan Set your graphics API to DirectX 11 before using the mod.

You can do this by deleting the mod and then setting it in your graphics options, or you can modify this line in your `re3_config.ini` in the game folder:
```
TargetPlatform=DirectX11
```
