### ISSUE TITLE
Request: improve the witcher3 first person mod by ScacikPL 

### ISSUE THREAD

**Issue by fuiop2000** [praydog/RE2-Mod-Framework#55]
@praydog Praydog can you make a better version of the first person mod by ScacikPL in the Witcher 3 that does not have as much enemy pop-in and smoother turning (does not oversteer) and a simulated roll (could be just a quick thrust forward and a dip) 

VG247 article: The Witcher 3 first person mode now supports combat!

https://www.vg247.com/2017/06/05/the-witcher-3-first-person-mod-now-supports-combat/

Be the Witcher with the tweaked first-person mod.

Remember that mod for The Witcher 3 last year that let you play in first-person?

Well it’s been updated to support combat now, so have fun with that.

SkacikPL released the mod sans combat last year, but said, “people wanted combat – people received combat.

“Besides, when combat was not available tons of people were asking me to make it available and now once that is available with the disclaimers that yes – it is bad, people are whining it is terrible.

“Oh well.”

In the description on their most recent video, SkacikPL reiterates that a lot of the features can be toggled and adjusted – like head bobbing and FOV – and points out that they’re one person with limited resources.

**Comment by RinMaru** [comment]
This is Only for RE engine games stop spamming

**Comment by fuiop2000** [comment]
i think Praydog could make a first person version of other games too, perhaps?

lots of games would benefit from a first person perspective that are third person only.

**Comment by RinMaru** [comment]
> i think Praydog could make a first person version of other games too, perhaps?
> 
> lots of games would benefit from a first person perspective that are third person only.

While i can see your point its probably best to ask this directly via anywhere else or just make one post having all your requests in a single place.

**Comment by fuiop2000** [comment]
is there anyway to communicate with praydog via other means, does he have email or twitter

**Comment by SkacikPL** [comment]
Well, this is amusing.

**Comment by fuiop2000** [comment]
@SkacikPL i'd really like the first person combat to be better in witcher3 like in your mod, maybe praydog can implement the first person fighting with RE2 mod methods

**Comment by SkacikPL** [comment]
> i mean even you admitted it wasn't done well in the VG247 article

Because there isn't anything to hide really, it is as best as it can get while being done on the game's proprietary scripting layer. There aren't many improvements that could be done using the approach i did and whilst sure - if you're really insistent on it, you could probably get better results via native code hacks and injections, i highly doubt anyone would do it at this point.

And this project here is called **Resident Evil 2** Mod Framework, so it's not really a good place to ask for Witcher 3 mods lol.

**Comment by fuiop2000** [comment]
is there anyway you can make the turning smoother in witcher3 so at least it does not turn like a tank i think i would at least enjoy the explore aspect in first person if it didn't Oversteer or snap to compass points or whatever is happening.

**Comment by SkacikPL** [comment]
Well, the mod offers you both autowalk and autopilot features to reduce manual movement to absolute minimum.

With autowalk you can just look into direction you want to walk in and press W once to correct your direction without overshooting and autopilot allows you to mark target point on map then have AI handle rest for you.

It's all in the mod description.

**Comment by fuiop2000** [comment]
can you try my request for AC:origins and AC:odyssey is there any way to make it first person like RE2, if you hold down a button you can do first person in discovery tour and maybe there is an easy way to transport the script function or command that does that in tour mode over to main game so you can try combat in first person and also climbing and seeing the arm movements too

https://github.com/praydog/RE2-Mod-Framework/issues/54

**Comment by fuiop2000** [comment]
@SkacikPL  can you try my request for AC:origins and AC:odyssey is there any way to make it first person like RE2, if you hold down a button you can do first person in discovery tour and maybe there is an easy way to transport the script function or command that does that in tour mode over to main game so you can try combat in first person and also climbing and seeing the arm movements too, would be amazing!

https://github.com/praydog/RE2-Mod-Framework/issues/54

**Comment by fuiop2000** [comment]
@SkacikPL can you at least direct me to where i should ask for this

**Comment by fuiop2000** [comment]
see its not just me this reddit user wants to see Unity in first person.

https://www.reddit.com/r/assassinscreed/comments/5lu9ws/possible_for_first_person_view_in_assassins_creed/
