### ISSUE TITLE
Mouse disabled.

### ISSUE THREAD

**Issue by githubisdumbwithstupidpasswordcrap** [praydog/RE2-Mod-Framework#6]
With this mod installed I can't click on any menus options (game or mod) and cant look around with the mouse.

**Comment by pacmanalex007** [comment]
I'm having the same issue :(

**Comment by FullBlood96** [comment]
Same problem here, some solution? I love the mod for what I see in videos is a shame.
Thanks anyway for this amazing mod, I hope it get fix soon to prove it myself

**Comment by SHIVAof** [comment]
Same for me, double cursor and it's non operable, can only move it

**Comment by GhostRiderYo** [comment]
Same here.

**Comment by Gonzaxpain** [comment]
Yep, same problem. I can run the game now (first attempts didn't work for some reason) but I can't change anything in the mod values with the mouse. I would like to change the camera speed and perhaps a little less camera shake.
Anyway, this is already fantastic, keep it up.

**Comment by davidgcs** [comment]
Same issue, waiting for solution. Im going to check the code for if i find something. Keep it up nice work dude

**Comment by K3R0ZEN** [comment]
Same here. ;-)

**Comment by GhostRiderYo** [comment]
So. My mouse is fixed. And know what? Its working with torrent edition... I mean cracked game works fine lol.

**Comment by K3R0ZEN** [comment]
@GhostRiderYo ,  And so how did you do it ?

**Comment by GhostRiderYo** [comment]
@K3R0ZEN , just downloaded cracked repack and it works.

**Comment by xXHenlolXx** [comment]
Same problem

**Comment by JayRad11** [comment]
Having the same issue with the double cursor and no ability to click any menu items while in game. Cursor will not move to the right quarter of the screen either. (Invisible barrier)

**Comment by zodiax01** [comment]
I'm using cracked repack..still didn't work..

**Comment by iamwes** [comment]
Same can't click anything in the framework. Managed to move the fov offset back to 30 by pressing tab but really want to turn Vignette off... Need to click it Tho and can't :(

**Comment by op1345** [comment]
Helped with the mouse crak fix от CODEX - http://www.mediafire.com/file/u8n1rm8hvasrwvw/Resident.Evil.2.Crackfix-CODEX.7z/file

**Comment by op1345** [comment]
crack fix helps with this problem

**Comment by Keith94** [comment]
So, as a solution, the mod should be updated to use pattern matching to work with any version of .exe?

**Comment by FullBlood96** [comment]
Yeah I download the crack fixed and now it works thanks a lot op1345 for yor answer

**Comment by zodiax01** [comment]
Yea true it works now! tqvm :)

**Comment by GhostRiderYo** [comment]
@zodiax01 try to use another repack. I tried couple of them. It dont work with repack from xatab. But working with one from igruxa.

**Comment by Gonzaxpain** [comment]
Does anyone have a link for the fix?

**Comment by davidgcs** [comment]
> Does anyone have a link for the fix?

this fixed it for me 
https://filecrypt.cc/Container/C8F1DB319F.html

**Comment by Gonzaxpain** [comment]
> 
> 
> > Does anyone have a link for the fix?
> 
> this fixed it for me
> https://filecrypt.cc/Container/C8F1DB319F.html

Thanks a lot, man, I'll try it tomorrow.

**Comment by iamwes** [comment]
This crackfix you lot posted a link for has stopped my game working at all now :-(
