### ISSUE TITLE
Crash on startup after update.

### ISSUE THREAD

**Issue by gir489** [praydog/RE2-Mod-Framework#62]
There was an update to RE3 a few days ago, and now when I load the game it just crashes to the desktop during the startup phase.

**Comment by praydog** [comment]
Can't seem to reproduce this. Check to see if your renderer got set to DX12 on accident, it's not supported in that mode. Not sure if there's any other settings that may cause compatibility issues with this.

If it still occurs after changing it, upload your `re2_fw_config.txt` and `re3_config.ini` so I can try to reproduce.
