### ISSUE TITLE
Make mod features work independently of each other

### ISSUE THREAD

**Issue by Keith94** [praydog/RE2-Mod-Framework#8]
Does the mod's options (e.g. FOV multiplier, vignette, etc.) depend on first-person being enabled to function, or can they still be manipulated with base third-person camera?

**Comment by praydog** [comment]
Only the vignette option works with FIrstPerson disabled right now.

**Comment by Keith94** [comment]
I see. So plans to make them function independently are in the works? If so, great :)

**Comment by odiminox** [comment]
@Keith94 I will look into creating  a new mod for manipulating camera settings.
