### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by mjk321** [praydog/RE2-Mod-Framework#9]
I've copied everything I have to copy in the folder, but it seems that it's not showing everything it should show in the REFramework menu nor switching to a first person perspective
![capture](https://user-images.githubusercontent.com/47407609/52388694-f85f3a80-2ad2-11e9-80f3-c42255f4daf2.JPG)
 I'm using the Japanese version of the game if that helps.

**Comment by praydog** [comment]
I'm working on something that should fix issues for different versions of the game, to protect against future updates. It might end up fixing the Japanese version when I'm done.

**Comment by mjk321** [comment]
thanks for the reply and for your work. I'll be waiting for the updates then.
